/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearInReviewRouteImport } from './routes/year-in-review'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ReadRouteImport } from './routes/read'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as OtherNotesRouteImport } from './routes/other-notes'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GigiRouteImport } from './routes/gigi'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddBookRouteImport } from './routes/add-book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteIdRouteImport } from './routes/note.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBookSearchRouteImport } from './routes/api/book-search'
import { Route as BookIdIndexRouteImport } from './routes/book.$id.index'
import { Route as BookIdStatusRouteImport } from './routes/book.$id.status'
import { Route as BookIdStatsRouteImport } from './routes/book.$id.stats'
import { Route as BookIdReadRouteImport } from './routes/book.$id.read'
import { Route as BookIdNotesRouteImport } from './routes/book.$id.notes'
import { Route as BookIdAboutRouteImport } from './routes/book.$id.about'
import { Route as ApiChatgptStatusRouteImport } from './routes/api/chatgpt/status'
import { Route as ApiChatgptRedirectUriRouteImport } from './routes/api/chatgpt/redirect-uri'
import { Route as ApiChatgptLoginRouteImport } from './routes/api/chatgpt/login'
import { Route as ApiChatgptExchangeRouteImport } from './routes/api/chatgpt/exchange'
import { Route as ApiChatgptDisconnectRouteImport } from './routes/api/chatgpt/disconnect'
import { Route as ApiChatgptCallbackRouteImport } from './routes/api/chatgpt/callback'
import { Route as ApiBookSearchBatchRouteImport } from './routes/api/book-search.batch'
import { Route as ApiAssetsIdRouteImport } from './routes/api/assets/$id'
import { Route as BookIdNotesIndexRouteImport } from './routes/book.$id.notes.index'
import { Route as BookIdNotesQuotesRouteImport } from './routes/book.$id.notes.quotes'
import { Route as BookIdNotesOtherRouteImport } from './routes/book.$id.notes.other'
import { Route as BookIdNotesNewRouteImport } from './routes/book.$id.notes.new'
import { Route as BookIdNotesChaptersRouteImport } from './routes/book.$id.notes.chapters'
import { Route as BookIdNotesAllRouteImport } from './routes/book.$id.notes.all'
import { Route as BookIdNotesNoteIdRouteImport } from './routes/book.$id.notes.$noteId'

const YearInReviewRoute = YearInReviewRouteImport.update({
  id: '/year-in-review',
  path: '/year-in-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherNotesRoute = OtherNotesRouteImport.update({
  id: '/other-notes',
  path: '/other-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GigiRoute = GigiRouteImport.update({
  id: '/gigi',
  path: '/gigi',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBookRoute = AddBookRouteImport.update({
  id: '/add-book',
  path: '/add-book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIdRoute = NoteIdRouteImport.update({
  id: '/note/$id',
  path: '/note/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookSearchRoute = ApiBookSearchRouteImport.update({
  id: '/api/book-search',
  path: '/api/book-search',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdIndexRoute = BookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdStatusRoute = BookIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdStatsRoute = BookIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdReadRoute = BookIdReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdNotesRoute = BookIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdAboutRoute = BookIdAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => BookIdRoute,
} as any)
const ApiChatgptStatusRoute = ApiChatgptStatusRouteImport.update({
  id: '/api/chatgpt/status',
  path: '/api/chatgpt/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptRedirectUriRoute = ApiChatgptRedirectUriRouteImport.update({
  id: '/api/chatgpt/redirect-uri',
  path: '/api/chatgpt/redirect-uri',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptLoginRoute = ApiChatgptLoginRouteImport.update({
  id: '/api/chatgpt/login',
  path: '/api/chatgpt/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptExchangeRoute = ApiChatgptExchangeRouteImport.update({
  id: '/api/chatgpt/exchange',
  path: '/api/chatgpt/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptDisconnectRoute = ApiChatgptDisconnectRouteImport.update({
  id: '/api/chatgpt/disconnect',
  path: '/api/chatgpt/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptCallbackRoute = ApiChatgptCallbackRouteImport.update({
  id: '/api/chatgpt/callback',
  path: '/api/chatgpt/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookSearchBatchRoute = ApiBookSearchBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => ApiBookSearchRoute,
} as any)
const ApiAssetsIdRoute = ApiAssetsIdRouteImport.update({
  id: '/api/assets/$id',
  path: '/api/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdNotesIndexRoute = BookIdNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookIdNotesRoute,
} as any)
const BookIdNotesQuotesRoute = BookIdNotesQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => BookIdNotesRoute,
} as any)
const BookIdNotesOtherRoute = BookIdNotesOtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => BookIdNotesRoute,
} as any)
const BookIdNotesNewRoute = BookIdNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BookIdNotesRoute,
} as any)
const BookIdNotesChaptersRoute = BookIdNotesChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => BookIdNotesRoute,
} as any)
const BookIdNotesAllRoute = BookIdNotesAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => BookIdNotesRoute,
} as any)
const BookIdNotesNoteIdRoute = BookIdNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => BookIdNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-book': typeof AddBookRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/gigi': typeof GigiRoute
  '/library': typeof LibraryRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/other-notes': typeof OtherNotesRoute
  '/quotes': typeof QuotesRoute
  '/read': typeof ReadRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/themes': typeof ThemesRoute
  '/year-in-review': typeof YearInReviewRoute
  '/api/book-search': typeof ApiBookSearchRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/book/$id': typeof BookIdRouteWithChildren
  '/note/$id': typeof NoteIdRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/book-search/batch': typeof ApiBookSearchBatchRoute
  '/api/chatgpt/callback': typeof ApiChatgptCallbackRoute
  '/api/chatgpt/disconnect': typeof ApiChatgptDisconnectRoute
  '/api/chatgpt/exchange': typeof ApiChatgptExchangeRoute
  '/api/chatgpt/login': typeof ApiChatgptLoginRoute
  '/api/chatgpt/redirect-uri': typeof ApiChatgptRedirectUriRoute
  '/api/chatgpt/status': typeof ApiChatgptStatusRoute
  '/book/$id/about': typeof BookIdAboutRoute
  '/book/$id/notes': typeof BookIdNotesRouteWithChildren
  '/book/$id/read': typeof BookIdReadRoute
  '/book/$id/stats': typeof BookIdStatsRoute
  '/book/$id/status': typeof BookIdStatusRoute
  '/book/$id/': typeof BookIdIndexRoute
  '/book/$id/notes/$noteId': typeof BookIdNotesNoteIdRoute
  '/book/$id/notes/all': typeof BookIdNotesAllRoute
  '/book/$id/notes/chapters': typeof BookIdNotesChaptersRoute
  '/book/$id/notes/new': typeof BookIdNotesNewRoute
  '/book/$id/notes/other': typeof BookIdNotesOtherRoute
  '/book/$id/notes/quotes': typeof BookIdNotesQuotesRoute
  '/book/$id/notes/': typeof BookIdNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-book': typeof AddBookRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/gigi': typeof GigiRoute
  '/library': typeof LibraryRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/other-notes': typeof OtherNotesRoute
  '/quotes': typeof QuotesRoute
  '/read': typeof ReadRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/themes': typeof ThemesRoute
  '/year-in-review': typeof YearInReviewRoute
  '/api/book-search': typeof ApiBookSearchRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/note/$id': typeof NoteIdRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/book-search/batch': typeof ApiBookSearchBatchRoute
  '/api/chatgpt/callback': typeof ApiChatgptCallbackRoute
  '/api/chatgpt/disconnect': typeof ApiChatgptDisconnectRoute
  '/api/chatgpt/exchange': typeof ApiChatgptExchangeRoute
  '/api/chatgpt/login': typeof ApiChatgptLoginRoute
  '/api/chatgpt/redirect-uri': typeof ApiChatgptRedirectUriRoute
  '/api/chatgpt/status': typeof ApiChatgptStatusRoute
  '/book/$id/about': typeof BookIdAboutRoute
  '/book/$id/read': typeof BookIdReadRoute
  '/book/$id/stats': typeof BookIdStatsRoute
  '/book/$id/status': typeof BookIdStatusRoute
  '/book/$id': typeof BookIdIndexRoute
  '/book/$id/notes/$noteId': typeof BookIdNotesNoteIdRoute
  '/book/$id/notes/all': typeof BookIdNotesAllRoute
  '/book/$id/notes/chapters': typeof BookIdNotesChaptersRoute
  '/book/$id/notes/new': typeof BookIdNotesNewRoute
  '/book/$id/notes/other': typeof BookIdNotesOtherRoute
  '/book/$id/notes/quotes': typeof BookIdNotesQuotesRoute
  '/book/$id/notes': typeof BookIdNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-book': typeof AddBookRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/gigi': typeof GigiRoute
  '/library': typeof LibraryRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/other-notes': typeof OtherNotesRoute
  '/quotes': typeof QuotesRoute
  '/read': typeof ReadRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/themes': typeof ThemesRoute
  '/year-in-review': typeof YearInReviewRoute
  '/api/book-search': typeof ApiBookSearchRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/book/$id': typeof BookIdRouteWithChildren
  '/note/$id': typeof NoteIdRoute
  '/api/assets/$id': typeof ApiAssetsIdRoute
  '/api/book-search/batch': typeof ApiBookSearchBatchRoute
  '/api/chatgpt/callback': typeof ApiChatgptCallbackRoute
  '/api/chatgpt/disconnect': typeof ApiChatgptDisconnectRoute
  '/api/chatgpt/exchange': typeof ApiChatgptExchangeRoute
  '/api/chatgpt/login': typeof ApiChatgptLoginRoute
  '/api/chatgpt/redirect-uri': typeof ApiChatgptRedirectUriRoute
  '/api/chatgpt/status': typeof ApiChatgptStatusRoute
  '/book/$id/about': typeof BookIdAboutRoute
  '/book/$id/notes': typeof BookIdNotesRouteWithChildren
  '/book/$id/read': typeof BookIdReadRoute
  '/book/$id/stats': typeof BookIdStatsRoute
  '/book/$id/status': typeof BookIdStatusRoute
  '/book/$id/': typeof BookIdIndexRoute
  '/book/$id/notes/$noteId': typeof BookIdNotesNoteIdRoute
  '/book/$id/notes/all': typeof BookIdNotesAllRoute
  '/book/$id/notes/chapters': typeof BookIdNotesChaptersRoute
  '/book/$id/notes/new': typeof BookIdNotesNewRoute
  '/book/$id/notes/other': typeof BookIdNotesOtherRoute
  '/book/$id/notes/quotes': typeof BookIdNotesQuotesRoute
  '/book/$id/notes/': typeof BookIdNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-book'
    | '/auth'
    | '/chapters'
    | '/gigi'
    | '/library'
    | '/notebook'
    | '/notes'
    | '/other-notes'
    | '/quotes'
    | '/read'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/themes'
    | '/year-in-review'
    | '/api/book-search'
    | '/api/chat'
    | '/api/health'
    | '/book/$id'
    | '/note/$id'
    | '/api/assets/$id'
    | '/api/book-search/batch'
    | '/api/chatgpt/callback'
    | '/api/chatgpt/disconnect'
    | '/api/chatgpt/exchange'
    | '/api/chatgpt/login'
    | '/api/chatgpt/redirect-uri'
    | '/api/chatgpt/status'
    | '/book/$id/about'
    | '/book/$id/notes'
    | '/book/$id/read'
    | '/book/$id/stats'
    | '/book/$id/status'
    | '/book/$id/'
    | '/book/$id/notes/$noteId'
    | '/book/$id/notes/all'
    | '/book/$id/notes/chapters'
    | '/book/$id/notes/new'
    | '/book/$id/notes/other'
    | '/book/$id/notes/quotes'
    | '/book/$id/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-book'
    | '/auth'
    | '/chapters'
    | '/gigi'
    | '/library'
    | '/notebook'
    | '/notes'
    | '/other-notes'
    | '/quotes'
    | '/read'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/themes'
    | '/year-in-review'
    | '/api/book-search'
    | '/api/chat'
    | '/api/health'
    | '/note/$id'
    | '/api/assets/$id'
    | '/api/book-search/batch'
    | '/api/chatgpt/callback'
    | '/api/chatgpt/disconnect'
    | '/api/chatgpt/exchange'
    | '/api/chatgpt/login'
    | '/api/chatgpt/redirect-uri'
    | '/api/chatgpt/status'
    | '/book/$id/about'
    | '/book/$id/read'
    | '/book/$id/stats'
    | '/book/$id/status'
    | '/book/$id'
    | '/book/$id/notes/$noteId'
    | '/book/$id/notes/all'
    | '/book/$id/notes/chapters'
    | '/book/$id/notes/new'
    | '/book/$id/notes/other'
    | '/book/$id/notes/quotes'
    | '/book/$id/notes'
  id:
    | '__root__'
    | '/'
    | '/add-book'
    | '/auth'
    | '/chapters'
    | '/gigi'
    | '/library'
    | '/notebook'
    | '/notes'
    | '/other-notes'
    | '/quotes'
    | '/read'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/themes'
    | '/year-in-review'
    | '/api/book-search'
    | '/api/chat'
    | '/api/health'
    | '/book/$id'
    | '/note/$id'
    | '/api/assets/$id'
    | '/api/book-search/batch'
    | '/api/chatgpt/callback'
    | '/api/chatgpt/disconnect'
    | '/api/chatgpt/exchange'
    | '/api/chatgpt/login'
    | '/api/chatgpt/redirect-uri'
    | '/api/chatgpt/status'
    | '/book/$id/about'
    | '/book/$id/notes'
    | '/book/$id/read'
    | '/book/$id/stats'
    | '/book/$id/status'
    | '/book/$id/'
    | '/book/$id/notes/$noteId'
    | '/book/$id/notes/all'
    | '/book/$id/notes/chapters'
    | '/book/$id/notes/new'
    | '/book/$id/notes/other'
    | '/book/$id/notes/quotes'
    | '/book/$id/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBookRoute: typeof AddBookRoute
  AuthRoute: typeof AuthRoute
  ChaptersRoute: typeof ChaptersRoute
  GigiRoute: typeof GigiRoute
  LibraryRoute: typeof LibraryRoute
  NotebookRoute: typeof NotebookRoute
  NotesRoute: typeof NotesRoute
  OtherNotesRoute: typeof OtherNotesRoute
  QuotesRoute: typeof QuotesRoute
  ReadRoute: typeof ReadRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  ThemesRoute: typeof ThemesRoute
  YearInReviewRoute: typeof YearInReviewRoute
  ApiBookSearchRoute: typeof ApiBookSearchRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BookIdRoute: typeof BookIdRouteWithChildren
  NoteIdRoute: typeof NoteIdRoute
  ApiAssetsIdRoute: typeof ApiAssetsIdRoute
  ApiChatgptCallbackRoute: typeof ApiChatgptCallbackRoute
  ApiChatgptDisconnectRoute: typeof ApiChatgptDisconnectRoute
  ApiChatgptExchangeRoute: typeof ApiChatgptExchangeRoute
  ApiChatgptLoginRoute: typeof ApiChatgptLoginRoute
  ApiChatgptRedirectUriRoute: typeof ApiChatgptRedirectUriRoute
  ApiChatgptStatusRoute: typeof ApiChatgptStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/year-in-review': {
      id: '/year-in-review'
      path: '/year-in-review'
      fullPath: '/year-in-review'
      preLoaderRoute: typeof YearInReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-notes': {
      id: '/other-notes'
      path: '/other-notes'
      fullPath: '/other-notes'
      preLoaderRoute: typeof OtherNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigi': {
      id: '/gigi'
      path: '/gigi'
      fullPath: '/gigi'
      preLoaderRoute: typeof GigiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-book': {
      id: '/add-book'
      path: '/add-book'
      fullPath: '/add-book'
      preLoaderRoute: typeof AddBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$id': {
      id: '/note/$id'
      path: '/note/$id'
      fullPath: '/note/$id'
      preLoaderRoute: typeof NoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/book-search': {
      id: '/api/book-search'
      path: '/api/book-search'
      fullPath: '/api/book-search'
      preLoaderRoute: typeof ApiBookSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id/': {
      id: '/book/$id/'
      path: '/'
      fullPath: '/book/$id/'
      preLoaderRoute: typeof BookIdIndexRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/status': {
      id: '/book/$id/status'
      path: '/status'
      fullPath: '/book/$id/status'
      preLoaderRoute: typeof BookIdStatusRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/stats': {
      id: '/book/$id/stats'
      path: '/stats'
      fullPath: '/book/$id/stats'
      preLoaderRoute: typeof BookIdStatsRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/read': {
      id: '/book/$id/read'
      path: '/read'
      fullPath: '/book/$id/read'
      preLoaderRoute: typeof BookIdReadRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/notes': {
      id: '/book/$id/notes'
      path: '/notes'
      fullPath: '/book/$id/notes'
      preLoaderRoute: typeof BookIdNotesRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/about': {
      id: '/book/$id/about'
      path: '/about'
      fullPath: '/book/$id/about'
      preLoaderRoute: typeof BookIdAboutRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/api/chatgpt/status': {
      id: '/api/chatgpt/status'
      path: '/api/chatgpt/status'
      fullPath: '/api/chatgpt/status'
      preLoaderRoute: typeof ApiChatgptStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt/redirect-uri': {
      id: '/api/chatgpt/redirect-uri'
      path: '/api/chatgpt/redirect-uri'
      fullPath: '/api/chatgpt/redirect-uri'
      preLoaderRoute: typeof ApiChatgptRedirectUriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt/login': {
      id: '/api/chatgpt/login'
      path: '/api/chatgpt/login'
      fullPath: '/api/chatgpt/login'
      preLoaderRoute: typeof ApiChatgptLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt/exchange': {
      id: '/api/chatgpt/exchange'
      path: '/api/chatgpt/exchange'
      fullPath: '/api/chatgpt/exchange'
      preLoaderRoute: typeof ApiChatgptExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt/disconnect': {
      id: '/api/chatgpt/disconnect'
      path: '/api/chatgpt/disconnect'
      fullPath: '/api/chatgpt/disconnect'
      preLoaderRoute: typeof ApiChatgptDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt/callback': {
      id: '/api/chatgpt/callback'
      path: '/api/chatgpt/callback'
      fullPath: '/api/chatgpt/callback'
      preLoaderRoute: typeof ApiChatgptCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/book-search/batch': {
      id: '/api/book-search/batch'
      path: '/batch'
      fullPath: '/api/book-search/batch'
      preLoaderRoute: typeof ApiBookSearchBatchRouteImport
      parentRoute: typeof ApiBookSearchRoute
    }
    '/api/assets/$id': {
      id: '/api/assets/$id'
      path: '/api/assets/$id'
      fullPath: '/api/assets/$id'
      preLoaderRoute: typeof ApiAssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id/notes/': {
      id: '/book/$id/notes/'
      path: '/'
      fullPath: '/book/$id/notes/'
      preLoaderRoute: typeof BookIdNotesIndexRouteImport
      parentRoute: typeof BookIdNotesRoute
    }
    '/book/$id/notes/quotes': {
      id: '/book/$id/notes/quotes'
      path: '/quotes'
      fullPath: '/book/$id/notes/quotes'
      preLoaderRoute: typeof BookIdNotesQuotesRouteImport
      parentRoute: typeof BookIdNotesRoute
    }
    '/book/$id/notes/other': {
      id: '/book/$id/notes/other'
      path: '/other'
      fullPath: '/book/$id/notes/other'
      preLoaderRoute: typeof BookIdNotesOtherRouteImport
      parentRoute: typeof BookIdNotesRoute
    }
    '/book/$id/notes/new': {
      id: '/book/$id/notes/new'
      path: '/new'
      fullPath: '/book/$id/notes/new'
      preLoaderRoute: typeof BookIdNotesNewRouteImport
      parentRoute: typeof BookIdNotesRoute
    }
    '/book/$id/notes/chapters': {
      id: '/book/$id/notes/chapters'
      path: '/chapters'
      fullPath: '/book/$id/notes/chapters'
      preLoaderRoute: typeof BookIdNotesChaptersRouteImport
      parentRoute: typeof BookIdNotesRoute
    }
    '/book/$id/notes/all': {
      id: '/book/$id/notes/all'
      path: '/all'
      fullPath: '/book/$id/notes/all'
      preLoaderRoute: typeof BookIdNotesAllRouteImport
      parentRoute: typeof BookIdNotesRoute
    }
    '/book/$id/notes/$noteId': {
      id: '/book/$id/notes/$noteId'
      path: '/$noteId'
      fullPath: '/book/$id/notes/$noteId'
      preLoaderRoute: typeof BookIdNotesNoteIdRouteImport
      parentRoute: typeof BookIdNotesRoute
    }
  }
}

interface ApiBookSearchRouteChildren {
  ApiBookSearchBatchRoute: typeof ApiBookSearchBatchRoute
}

const ApiBookSearchRouteChildren: ApiBookSearchRouteChildren = {
  ApiBookSearchBatchRoute: ApiBookSearchBatchRoute,
}

const ApiBookSearchRouteWithChildren = ApiBookSearchRoute._addFileChildren(
  ApiBookSearchRouteChildren,
)

interface BookIdNotesRouteChildren {
  BookIdNotesNoteIdRoute: typeof BookIdNotesNoteIdRoute
  BookIdNotesAllRoute: typeof BookIdNotesAllRoute
  BookIdNotesChaptersRoute: typeof BookIdNotesChaptersRoute
  BookIdNotesNewRoute: typeof BookIdNotesNewRoute
  BookIdNotesOtherRoute: typeof BookIdNotesOtherRoute
  BookIdNotesQuotesRoute: typeof BookIdNotesQuotesRoute
  BookIdNotesIndexRoute: typeof BookIdNotesIndexRoute
}

const BookIdNotesRouteChildren: BookIdNotesRouteChildren = {
  BookIdNotesNoteIdRoute: BookIdNotesNoteIdRoute,
  BookIdNotesAllRoute: BookIdNotesAllRoute,
  BookIdNotesChaptersRoute: BookIdNotesChaptersRoute,
  BookIdNotesNewRoute: BookIdNotesNewRoute,
  BookIdNotesOtherRoute: BookIdNotesOtherRoute,
  BookIdNotesQuotesRoute: BookIdNotesQuotesRoute,
  BookIdNotesIndexRoute: BookIdNotesIndexRoute,
}

const BookIdNotesRouteWithChildren = BookIdNotesRoute._addFileChildren(
  BookIdNotesRouteChildren,
)

interface BookIdRouteChildren {
  BookIdAboutRoute: typeof BookIdAboutRoute
  BookIdNotesRoute: typeof BookIdNotesRouteWithChildren
  BookIdReadRoute: typeof BookIdReadRoute
  BookIdStatsRoute: typeof BookIdStatsRoute
  BookIdStatusRoute: typeof BookIdStatusRoute
  BookIdIndexRoute: typeof BookIdIndexRoute
}

const BookIdRouteChildren: BookIdRouteChildren = {
  BookIdAboutRoute: BookIdAboutRoute,
  BookIdNotesRoute: BookIdNotesRouteWithChildren,
  BookIdReadRoute: BookIdReadRoute,
  BookIdStatsRoute: BookIdStatsRoute,
  BookIdStatusRoute: BookIdStatusRoute,
  BookIdIndexRoute: BookIdIndexRoute,
}

const BookIdRouteWithChildren =
  BookIdRoute._addFileChildren(BookIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBookRoute: AddBookRoute,
  AuthRoute: AuthRoute,
  ChaptersRoute: ChaptersRoute,
  GigiRoute: GigiRoute,
  LibraryRoute: LibraryRoute,
  NotebookRoute: NotebookRoute,
  NotesRoute: NotesRoute,
  OtherNotesRoute: OtherNotesRoute,
  QuotesRoute: QuotesRoute,
  ReadRoute: ReadRoute,
  RecommendationsRoute: RecommendationsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  ThemesRoute: ThemesRoute,
  YearInReviewRoute: YearInReviewRoute,
  ApiBookSearchRoute: ApiBookSearchRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  BookIdRoute: BookIdRouteWithChildren,
  NoteIdRoute: NoteIdRoute,
  ApiAssetsIdRoute: ApiAssetsIdRoute,
  ApiChatgptCallbackRoute: ApiChatgptCallbackRoute,
  ApiChatgptDisconnectRoute: ApiChatgptDisconnectRoute,
  ApiChatgptExchangeRoute: ApiChatgptExchangeRoute,
  ApiChatgptLoginRoute: ApiChatgptLoginRoute,
  ApiChatgptRedirectUriRoute: ApiChatgptRedirectUriRoute,
  ApiChatgptStatusRoute: ApiChatgptStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
