/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ReadRouteImport } from './routes/read'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as OtherNotesRouteImport } from './routes/other-notes'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GigiRouteImport } from './routes/gigi'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as AddBookRouteImport } from './routes/add-book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteIdRouteImport } from './routes/note.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as BookIdIndexRouteImport } from './routes/book.$id.index'
import { Route as BookIdStatusRouteImport } from './routes/book.$id.status'
import { Route as BookIdStatsRouteImport } from './routes/book.$id.stats'
import { Route as BookIdReadRouteImport } from './routes/book.$id.read'
import { Route as BookIdNotesRouteImport } from './routes/book.$id.notes'
import { Route as BookIdAboutRouteImport } from './routes/book.$id.about'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherNotesRoute = OtherNotesRouteImport.update({
  id: '/other-notes',
  path: '/other-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GigiRoute = GigiRouteImport.update({
  id: '/gigi',
  path: '/gigi',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBookRoute = AddBookRouteImport.update({
  id: '/add-book',
  path: '/add-book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIdRoute = NoteIdRouteImport.update({
  id: '/note/$id',
  path: '/note/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdIndexRoute = BookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdStatusRoute = BookIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdStatsRoute = BookIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdReadRoute = BookIdReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdNotesRoute = BookIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => BookIdRoute,
} as any)
const BookIdAboutRoute = BookIdAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => BookIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-book': typeof AddBookRoute
  '/chapters': typeof ChaptersRoute
  '/gigi': typeof GigiRoute
  '/library': typeof LibraryRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/other-notes': typeof OtherNotesRoute
  '/quotes': typeof QuotesRoute
  '/read': typeof ReadRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/themes': typeof ThemesRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$id': typeof BookIdRouteWithChildren
  '/note/$id': typeof NoteIdRoute
  '/book/$id/about': typeof BookIdAboutRoute
  '/book/$id/notes': typeof BookIdNotesRoute
  '/book/$id/read': typeof BookIdReadRoute
  '/book/$id/stats': typeof BookIdStatsRoute
  '/book/$id/status': typeof BookIdStatusRoute
  '/book/$id/': typeof BookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-book': typeof AddBookRoute
  '/chapters': typeof ChaptersRoute
  '/gigi': typeof GigiRoute
  '/library': typeof LibraryRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/other-notes': typeof OtherNotesRoute
  '/quotes': typeof QuotesRoute
  '/read': typeof ReadRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/themes': typeof ThemesRoute
  '/api/chat': typeof ApiChatRoute
  '/note/$id': typeof NoteIdRoute
  '/book/$id/about': typeof BookIdAboutRoute
  '/book/$id/notes': typeof BookIdNotesRoute
  '/book/$id/read': typeof BookIdReadRoute
  '/book/$id/stats': typeof BookIdStatsRoute
  '/book/$id/status': typeof BookIdStatusRoute
  '/book/$id': typeof BookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-book': typeof AddBookRoute
  '/chapters': typeof ChaptersRoute
  '/gigi': typeof GigiRoute
  '/library': typeof LibraryRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/other-notes': typeof OtherNotesRoute
  '/quotes': typeof QuotesRoute
  '/read': typeof ReadRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/themes': typeof ThemesRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$id': typeof BookIdRouteWithChildren
  '/note/$id': typeof NoteIdRoute
  '/book/$id/about': typeof BookIdAboutRoute
  '/book/$id/notes': typeof BookIdNotesRoute
  '/book/$id/read': typeof BookIdReadRoute
  '/book/$id/stats': typeof BookIdStatsRoute
  '/book/$id/status': typeof BookIdStatusRoute
  '/book/$id/': typeof BookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-book'
    | '/chapters'
    | '/gigi'
    | '/library'
    | '/notebook'
    | '/notes'
    | '/other-notes'
    | '/quotes'
    | '/read'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/themes'
    | '/api/chat'
    | '/book/$id'
    | '/note/$id'
    | '/book/$id/about'
    | '/book/$id/notes'
    | '/book/$id/read'
    | '/book/$id/stats'
    | '/book/$id/status'
    | '/book/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-book'
    | '/chapters'
    | '/gigi'
    | '/library'
    | '/notebook'
    | '/notes'
    | '/other-notes'
    | '/quotes'
    | '/read'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/themes'
    | '/api/chat'
    | '/note/$id'
    | '/book/$id/about'
    | '/book/$id/notes'
    | '/book/$id/read'
    | '/book/$id/stats'
    | '/book/$id/status'
    | '/book/$id'
  id:
    | '__root__'
    | '/'
    | '/add-book'
    | '/chapters'
    | '/gigi'
    | '/library'
    | '/notebook'
    | '/notes'
    | '/other-notes'
    | '/quotes'
    | '/read'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/themes'
    | '/api/chat'
    | '/book/$id'
    | '/note/$id'
    | '/book/$id/about'
    | '/book/$id/notes'
    | '/book/$id/read'
    | '/book/$id/stats'
    | '/book/$id/status'
    | '/book/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBookRoute: typeof AddBookRoute
  ChaptersRoute: typeof ChaptersRoute
  GigiRoute: typeof GigiRoute
  LibraryRoute: typeof LibraryRoute
  NotebookRoute: typeof NotebookRoute
  NotesRoute: typeof NotesRoute
  OtherNotesRoute: typeof OtherNotesRoute
  QuotesRoute: typeof QuotesRoute
  ReadRoute: typeof ReadRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  ThemesRoute: typeof ThemesRoute
  ApiChatRoute: typeof ApiChatRoute
  BookIdRoute: typeof BookIdRouteWithChildren
  NoteIdRoute: typeof NoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-notes': {
      id: '/other-notes'
      path: '/other-notes'
      fullPath: '/other-notes'
      preLoaderRoute: typeof OtherNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigi': {
      id: '/gigi'
      path: '/gigi'
      fullPath: '/gigi'
      preLoaderRoute: typeof GigiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-book': {
      id: '/add-book'
      path: '/add-book'
      fullPath: '/add-book'
      preLoaderRoute: typeof AddBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$id': {
      id: '/note/$id'
      path: '/note/$id'
      fullPath: '/note/$id'
      preLoaderRoute: typeof NoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id/': {
      id: '/book/$id/'
      path: '/'
      fullPath: '/book/$id/'
      preLoaderRoute: typeof BookIdIndexRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/status': {
      id: '/book/$id/status'
      path: '/status'
      fullPath: '/book/$id/status'
      preLoaderRoute: typeof BookIdStatusRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/stats': {
      id: '/book/$id/stats'
      path: '/stats'
      fullPath: '/book/$id/stats'
      preLoaderRoute: typeof BookIdStatsRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/read': {
      id: '/book/$id/read'
      path: '/read'
      fullPath: '/book/$id/read'
      preLoaderRoute: typeof BookIdReadRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/notes': {
      id: '/book/$id/notes'
      path: '/notes'
      fullPath: '/book/$id/notes'
      preLoaderRoute: typeof BookIdNotesRouteImport
      parentRoute: typeof BookIdRoute
    }
    '/book/$id/about': {
      id: '/book/$id/about'
      path: '/about'
      fullPath: '/book/$id/about'
      preLoaderRoute: typeof BookIdAboutRouteImport
      parentRoute: typeof BookIdRoute
    }
  }
}

interface BookIdRouteChildren {
  BookIdAboutRoute: typeof BookIdAboutRoute
  BookIdNotesRoute: typeof BookIdNotesRoute
  BookIdReadRoute: typeof BookIdReadRoute
  BookIdStatsRoute: typeof BookIdStatsRoute
  BookIdStatusRoute: typeof BookIdStatusRoute
  BookIdIndexRoute: typeof BookIdIndexRoute
}

const BookIdRouteChildren: BookIdRouteChildren = {
  BookIdAboutRoute: BookIdAboutRoute,
  BookIdNotesRoute: BookIdNotesRoute,
  BookIdReadRoute: BookIdReadRoute,
  BookIdStatsRoute: BookIdStatsRoute,
  BookIdStatusRoute: BookIdStatusRoute,
  BookIdIndexRoute: BookIdIndexRoute,
}

const BookIdRouteWithChildren =
  BookIdRoute._addFileChildren(BookIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBookRoute: AddBookRoute,
  ChaptersRoute: ChaptersRoute,
  GigiRoute: GigiRoute,
  LibraryRoute: LibraryRoute,
  NotebookRoute: NotebookRoute,
  NotesRoute: NotesRoute,
  OtherNotesRoute: OtherNotesRoute,
  QuotesRoute: QuotesRoute,
  ReadRoute: ReadRoute,
  RecommendationsRoute: RecommendationsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  ThemesRoute: ThemesRoute,
  ApiChatRoute: ApiChatRoute,
  BookIdRoute: BookIdRouteWithChildren,
  NoteIdRoute: NoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
